### ISSUE TITLE
 Upgrade Flutter to 3.24.1 version

### ISSUE THREAD

**Issue by azhezzzz** [instrumentisto/flutter-docker-image#16]
Can update Flutter to version 3.24.1 ?  
Some issues here appeared in 3.24.0 and were solved in 3.24.1

**Comment by tyranron** [comment]
Releases as [3.24.1-androidsdk34-r0](https://github.com/instrumentisto/flutter-docker-image/releases/tag/3.24.1-androidsdk34-r0).
