### ISSUE TITLE
cannot pull the image 

### ISSUE THREAD

**Issue by kanghk21** [instrumentisto/flutter-docker-image#19]
$ docker pull instrumentisto/flutter-docker-image:3.27.1                                                                                                                
Error response from daemon: pull access denied for instrumentisto/flutter-docker-image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by kanghk21** [comment]
I will try this again in new pc

**Comment by tyranron** [comment]
@kanghk21 it's `instrumentisto/flutter`.
